[{
    hintSilent format ["
        RPM     %1 <br/>
        THRUST  %2", 
    vehicle player getSoundController "rpm", 
    vehicle player getSoundController "thrust"
    ];
}, 0, []] call CBA_fnc_addPerFrameHandler;


["debugRPM", "OnEachFrame", {
    hintSilent format ["
        RPM          %1 \n
        THRUST       %2 \n
        engineeffectivity    %3"
    ,
    vehicle player getSoundController "rpm", 
    vehicle player getSoundController "thrust",
    vehicle player getSoundController "engineeffectivity"
    ];
}] call BIS_fnc_addStackedEventHandler;


[["rpm",568.582],
["randomizer",0.342661],
["speed",0],
["thrust",0],
["campos",0],
["engineon",1],
["rotorspeed",0],
["rotorthrust",0],
["angvelocity",0],
["gmeterz",0.000220757],
["roughness",0.05],
["dustness",0.02],
["damper0",0.60262],
["damper1",0.546897],
["damper2",0.545675],
["damper3",0.556805],
["rock",0],
["sand",0],
["grass",0],
["mud",0],
["gravel",0],
["asphalt",1],
["gear",0],
["flaps",0],
["rotpos",0],
["water",0],
["apu",0],
["batteries",0],
["rpmstarter",0],
["rpm1",0],
["rpmstarter1",0],
["motordamage",0],
["transmissiondamage",0],
["rotorbrake",0],
["slingloadactive",0],
["latslip",-0.000140699],
["latslipdrive",-0.000140699],
["longslip",0],
["longslipdrive",0],
["scrubland",0],
["scrubobject",0],
["scrubtree",0],
["scrubbuilding",0],
["scrubarmor",0],
["engineeffectivity",0.0125344],
["rain",0],
["wind",0.299125],
["lateralmovement",0],
["playerpos",0],
["rotordamage",0],
["distance",0.472197],
["machcone",1],
["camint",1],
["camext",0],
["houses",0],
["meadow",1],
["forest",0],
["trees",0],
["altRadar",1.43961],
["acceleration",0],
["CustomSoundController1",0],
["CustomSoundController2",0],
["CustomSoundController3",0],
["CustomSoundController4",0],
["CustomSoundController5",0],
["CustomSoundController6",0],
["CustomSoundController7",0],
["CustomSoundController8",0],
["CustomSoundController9",0],
["CustomSoundController10",0],
["CustomSoundController11",0],
["CustomSoundController12",0],
["CustomSoundController13",0],
["CustomSoundController14",0],
["CustomSoundController15",0],
["CustomSoundController16",0],
["CustomSoundController17",0],
["CustomSoundController18",0],
["CustomSoundController19",0],
["CustomSoundController20",0],
["CustomSoundController21",0],
["CustomSoundController22",0],
["CustomSoundController23",0],
["CustomSoundController24",0],
["CustomSoundController25",0],
["CustomSoundController26",0],
["CustomSoundController27",0],
["CustomSoundController28",0],
["CustomSoundController29",0],
["CustomSoundController30",0],
["CustomSoundController31",0],
["CustomSoundController32",0]]